### ISSUE TITLE
Resizing an image with a color space that does not allow output results in NULL image being returned.

### ISSUE THREAD

**Issue by clawoo** [vilanovi/UIImage-Additions#11]
Trying to resize the attached image results in a NULL response because the color space does not allow output.

The attached image (in case github's processing messes it up) has the following color space:
`<CGColorSpace 0x170627960> (kCGColorSpaceICCBased; kCGColorSpaceModelRGB; Apple Wide Color Sharing Profile)`

Checking via CGColorSpaceSupportsOutput(colorSpaceRef) returns false.

My solution is to check whether the color space supports output and if it doesn't, just default to the RGB color space:

```    CGColorSpaceRef colorSpaceRef = CGImageGetColorSpace(imageRef);
    if (!CGColorSpaceSupportsOutput(colorSpaceRef))
    {
        colorSpaceRef = CGColorSpaceCreateDeviceRGB();
    }
    // Build a context that's the same dimensions as the new size
    CGContextRef bitmap = CGBitmapContextCreate(NULL,
                                                newRect.size.width,
                                                newRect.size.height,
                                                CGImageGetBitsPerComponent(imageRef),
                                                0,
                                                colorSpaceRef,
                                                bitmapInfo);
```

![img_0088](https://cloud.githubusercontent.com/assets/380846/22477446/c5b176bc-e7ee-11e6-8990-7d77c1125b7d.PNG)

**Comment by clawoo** [comment]
The pull request is here: https://github.com/vilanovi/UIImage-Additions/pull/12

**Comment by vilanovi** [comment]
Perfect, thanks for taking care of it.
