### ISSUE TITLE
Something In This Category Crashes Xcode

### ISSUE THREAD

**Issue by inb4ohnoes** [vilanovi/UIImage-Additions#7]
Not an issue with this category itself probably, but it seems that an invalid character somewhere in the comments here crashes Xcode. Just thought I should give you a heads up.

Upon further investigation, it seems to be this 
![screen shot 2015-02-22 at 5 18 17 pm](https://cloud.githubusercontent.com/assets/1714873/6320827/dd5c2436-bab6-11e4-83af-415224396340.png)

**Comment by vilanovi** [comment]
Thanks! Going to correct it right now!

**Comment by vilanovi** [comment]
Ok! fixed and new cocoa pod released on version 2.0.1. Thanks!
